services:
    app:
        build:
            context: .
        container_name: laravel_app
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.laravel.rule=Host(`forum.test`)"
            - "traefik.http.services.laravel.loadbalancer.server.port=80"
        volumes:
            - .:/var/www/html
        networks:
            - laravel
        depends_on:
            - mysql

    mysql:
        image: mysql:5.7
        container_name: laravel_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: forum
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
            - ./forum.sql:/docker-entrypoint-initdb.d/forum.sql
        networks:
            - laravel

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: unless-stopped
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "8080:80"
        depends_on:
            - mysql
        networks:
            - laravel

    traefik:
        image: traefik:v2.2
        container_name: traefik
        command:
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "--entrypoints.web.address=:80"
        ports:
            - "80:80"
            - "8081:8080"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
        networks:
            - laravel

networks:
    laravel:

volumes:
    mysql_data:
